### ISSUE TITLE
player isnt teleported to last location after login if the server have been restarted

### ISSUE THREAD

**Issue by DisMaiT** [KarmaConfigs/page#20] opened 2021-10-08 20:20 UTC
player isnt teleported to last location after login if the server have been restarted

**Comment by KarmaConfigs** [comment] 2021-12-25 02:04
This is because when the server is restarted and there are players in the server, they won't actually leave the server. LockLogin listens for when an user leaves the server ( or gets kicked ) to store his last location. This won't be fixed as it is not a bug

**Closed by KarmaConfigs** 2021-12-25 02:04 UTC
